### ISSUE TITLE
Define the logo

### ISSUE THREAD

**Issue by raphaelkieling** [raphaelkieling/doctorenv#1]
Today we are using a temporary icon in the README, we should create a proposal:
- Be aligned with the name `Doctor env`
- SVG if possible

Any suggestion is welcome, minimalist, 3d or anything else.

**Comment by harshvyas-22** [comment]
i would love to contribute assign it to me

**Comment by raphaelkieling** [comment]
Ohh, sure assigned, would be a pleasure to have your contribution!
