### ISSUE TITLE
Adding contributors in the README

### ISSUE THREAD

**Issue by raphaelkieling** [raphaelkieling/doctorenv#6]
Use the tool: https://github.com/all-contributors/cli to show all the contributors, hopefully in the future we can have a lot of them 😄

**Comment by GosuCode** [comment]
I'll be working on this !

**Comment by Virtual4087** [comment]
I'm willing to work on this. Can you assign this to me?

**Comment by dakshsinghrathore** [comment]
@kielingraphael Kindly assign me this issue !

**Comment by raphaelkieling** [comment]
Thanks sir! Sure, the project is to small is too much for any kinda of bureaucracy

**Comment by raphaelkieling** [comment]
I will keep this in progress a bit since i cannot see the contributors yet, as soon as i review the rest of the stuff i will check if it works properly using the bot.

ps: now i can see, fixed.
